stages:
  - build
  - test

image: maven:3.8.6-openjdk-11

build-job:
  stage: build
  script:
    - mvn compile

test-job:
  stage: test
  script:
    - mvn test

sast-job:
  stage: test
  script:
    - mvn org.owasp:dependency-check-maven:check